context:
  version: "0.2.3"

package:
  name: polars-io-tools
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/54/07/8902126eb4e473d33bc788fd30a98c2377599b639cacae8bab78d9aa2948/polars_io_tools-${{ version }}.tar.gz
  sha256: 4ccb3b258a123be3f6ee90dbff676ddc28376460af76cb0740f69f53a2181950

build:
  number: 0
  python:
    version_independent: true
  script:
    - if: unix
      then: export PYO3_PYTHON="$PYTHON"
      else: set "PYO3_PYTHON=%PYTHON%"
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: is_abi3 and not is_python_min

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python ${{ python_min }}.*
        - cross-python_${{ target_platform }}
        - crossenv
        - hatchling
        - hatch-rs
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-rs
    - if: is_abi3
      then:
        - python-abi3
  run:
    - python >=${{ python_min }}
    - packaging
    - polars
    - portion
    - pydantic

tests:
  - python:
      imports:
        - polars_io_tools
      # deltalake 1.5.0 has macOS WHEEL tags for macosx_26_0,
      # which makes pip check fail on older CI runners despite valid imports.
      pip_check: ${{ not osx }}
      python_version:
        - ${{ python_min }}.*
        - "*"
  - if: is_abi3
    then:
      script:
        - if: win
          then: abi3audit %SP_DIR%/polars_io_tools/polars_io_tools.pyd -s -v --assume-minimum-abi3 ${{ python_min }}
          else: abi3audit $SP_DIR/polars_io_tools/polars_io_tools.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}
      requirements:
        run:
          - python >=${{ python_min }}
          - abi3audit

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Custom parsing extensions for lazy polars
  homepage: https://github.com/Point72/polars-io-tools
  repository: https://github.com/Point72/polars-io-tools

extra:
  recipe-maintainers:
    - hintse
    - arhamchopra
    - ptomecek
    - timkpaine
